/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientPoseRouteImport } from './routes/client.pose'
import { Route as ClientMatchesRouteImport } from './routes/client.matches'
import { Route as ClientDiscoverRouteImport } from './routes/client.discover'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as ClientTrainerIdRouteImport } from './routes/client.trainer.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPoseRoute = ClientPoseRouteImport.update({
  id: '/client/pose',
  path: '/client/pose',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMatchesRoute = ClientMatchesRouteImport.update({
  id: '/client/matches',
  path: '/client/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDiscoverRoute = ClientDiscoverRouteImport.update({
  id: '/client/discover',
  path: '/client/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/client/bookings',
  path: '/client/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTrainerIdRoute = ClientTrainerIdRouteImport.update({
  id: '/client/trainer/$id',
  path: '/client/trainer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/discover': typeof ClientDiscoverRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/pose': typeof ClientPoseRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trainer/$id': typeof ClientTrainerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/discover': typeof ClientDiscoverRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/pose': typeof ClientPoseRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trainer/$id': typeof ClientTrainerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/discover': typeof ClientDiscoverRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/pose': typeof ClientPoseRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/trainer/$id': typeof ClientTrainerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/client/bookings'
    | '/client/dashboard'
    | '/client/discover'
    | '/client/matches'
    | '/client/pose'
    | '/client/profile'
    | '/client/trainer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/client/bookings'
    | '/client/dashboard'
    | '/client/discover'
    | '/client/matches'
    | '/client/pose'
    | '/client/profile'
    | '/client/trainer/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/client/bookings'
    | '/client/dashboard'
    | '/client/discover'
    | '/client/matches'
    | '/client/pose'
    | '/client/profile'
    | '/client/trainer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientDiscoverRoute: typeof ClientDiscoverRoute
  ClientMatchesRoute: typeof ClientMatchesRoute
  ClientPoseRoute: typeof ClientPoseRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientTrainerIdRoute: typeof ClientTrainerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/pose': {
      id: '/client/pose'
      path: '/client/pose'
      fullPath: '/client/pose'
      preLoaderRoute: typeof ClientPoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/matches': {
      id: '/client/matches'
      path: '/client/matches'
      fullPath: '/client/matches'
      preLoaderRoute: typeof ClientMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/discover': {
      id: '/client/discover'
      path: '/client/discover'
      fullPath: '/client/discover'
      preLoaderRoute: typeof ClientDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/client/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/trainer/$id': {
      id: '/client/trainer/$id'
      path: '/client/trainer/$id'
      fullPath: '/client/trainer/$id'
      preLoaderRoute: typeof ClientTrainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ClientBookingsRoute: ClientBookingsRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientDiscoverRoute: ClientDiscoverRoute,
  ClientMatchesRoute: ClientMatchesRoute,
  ClientPoseRoute: ClientPoseRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientTrainerIdRoute: ClientTrainerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
